apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab155
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/lab155"
