apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lab1511pod
  name: lab1511pod
  namespace: access
spec:
  serviceAccountName: lab1511access
  nodeName: kube-node1
  containers:
  - image: busybox
    name: lab159pod
    args:
    - sleep
    - infinity
    imagePullPolicy: IfNotPresent
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
