---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: lab1511access
  namespace: access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: role1511
  namespace: access
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: lab1511role
  namespace: access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role1511
subjects:
- kind: ServiceAccount
  name: lab1511access
  namespace: access
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lab1511pod
  name: lab1511pod
  namespace: access
spec:
  serviceAccountName: lab1511access
  nodeName: kube-node1
  containers:
  - image: busybox
    name: lab159pod
    args:
    - sleep
    - infinity
    imagePullPolicy: IfNotPresent
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
