apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: lab1511role
  namespace: access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role1511
subjects:
- kind: ServiceAccount
  name: lab1511access
  namespace: access
