apiVersion: v1
kind: Pod
metadata:
  name: lab1512pod
spec:
  nodeName: kube-node2
  imagePullSecrets: 
  - name:  docker-secret
  containers:
  - name: nginx
    image: nginx:1.14.2
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 80
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "db"
    effect: "NoSchedule"
