---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: limited
spec: {}
status: {}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: quotalimit
  namespace: limited
spec:
  hard:
    memory: 1G
    pods: "5"
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lab158deploy
    team: sander
  name: lab158deploy
  namespace: limited
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab158deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lab158deploy
    spec:
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
