apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lab157access
    access: "true"
  name: lab157access
  namespace: access
spec:
  nodeName: kube-node1
  containers:
  - image: busybox
    name: lab157access
    args:
    - sleep
    - infinity
    imagePullPolicy: IfNotPresent
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
