apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lab157web
  name: lab157web
  namespace: restricted
spec:
  containers:
  - image: nginx:1.14.2
    name: lab157web
    imagePullPolicy: IfNotPresent
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
