apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lab156deploy
  name: lab156deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab156deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lab156deploy
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
status: {}
